version: '3'
services:
  connect:
     build: .
     ports:
      - "8080:8080"
     links:
      - zipkin:zipkin
     environment:
        APP_PORT: 8080
        KAFKA_BROKERS: localhost:9092
        SVC_TRACING_ZIPKIN: http://localhost:9411

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.11.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  kafka-manager:
    image: dockerkafka/kafka-manager
    environment:
      - ZK_HOSTS=zookeeper:2181
    ports:
      - "9000:9000"
    links:
      - zookeeper:zookeeper
      - kafka:kafka