version: '3'
services:
  connect:
    build: .
    ports:
     - "8080:8080"
    links:
     - zipkin:zipkin
    environment:
      APP_PORT: 8080
      KAFKA_BROKERS: localhost:9092
      SVC_TRACING_ZIPKIN: http://localhost:9411
    depends_on:
      - kafka    

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  kafka:
    container_name: kafka
    image: landoop/fast-data-dev:latest
    ports:
      - 2181:2181
      - 3030:3030
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585
      - 9092:9092
    environment:
      - ADV_HOST=localhost